stages:
  - test_prep
  - test
  - build
  - publish

include:
  - project: 'Northern.tech/Mender/mendertesting'
    file: '.gitlab-ci-check-golang-lint.yml'
  - project: 'Northern.tech/Mender/mendertesting'
    file: '.gitlab-ci-check-golang-unittests.yml'
  - component: gitlab.com/Northern.tech/Mender/mendertesting/commit-lint@master
  - component: gitlab.com/Northern.tech/Mender/mendertesting/backwards-compatible-yocto@master
  - project: 'Northern.tech/Mender/mendertesting'
    file: '.gitlab-ci-check-license.yml'
  - project: 'Northern.tech/Mender/mendertesting'
    file: '.gitlab-ci-github-status-updates.yml'
  - project: Northern.tech/Mender/mendertesting
    file:
      - qa-common/runner.yml
      - qa-common/retry.yml

default:
  tags: !reference [.qa-common-default-runner, tags]
  retry: !reference [.qa-common-default-retry, retry]

build:make:
  stage: build
  needs: []
  image: golang:1.23-alpine
  before_script:
    - apk add --update git make gcc pkgconfig libc-dev glib-dev
  script:
    - make build
